
title: Joey Codes
url: 'https://joeycodes.tech'
baseurl: '/' #change it according to your repository name
markdown: kramdown
remote_theme: jekyller/PanelCV



# Profile information
yourname: Joey Chung  ## put your name
title: 'Blockchain & Full Stack Engineer'  ## your title
location: Bay Area, CA


## Social Profiles
linkedin: http://www.linkedin.com/in/jchung05  ## your linkedin account url
github: https://github.com/jchung05
medium: https://medium.com/@joeychung960
twitter: https://twitter.com/@CountChococat



# Update all the sections by editing the files inside _includes folder.
