
title: Joey Codes
url: 'https://joeycodes.tech'
baseurl: '/' #change it according to your repository name



# Profile information
yourname: Joey Chung  ## put your name
title: 'Web & Blockchain Developer'  ## your title
location: Bay Area, CA


## Social Profiles
linkedin: http://www.linkedin.com/in/jchung05  ## your linkedin account url
github: https://github.com/jchung05



# Update all the sections by editing the files inside _includes folder.
